version: "3.0"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    depends_on:
      - db
  db:
    image: library/mysql:8.0.22
    ports:
      - '3306:3306'
    restart: 'always'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'api_backend'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      expose: '3306'
volumes:
  db_data: {}
