# Render yaml here - https://editor.swagger.io/
swagger: "2.0"
info:
  description: "This is how to use the API backend that returns JSON"
  version: "1.0.0"
  title: "API Backend"
  contact:
    email: "tom.mcfarlane97@gmail.com"
host: "localhost:8080"
basePath: "/"
tags:
  - name: "user"
    description: "Operations about user"
    externalDocs:
      description: "Find out more user"
      url: "http://swagger.io"
  - name: "note"
    description: "Operations about note"
    externalDocs:
      description: "Find out about note"
      url: "http://swagger.io"
schemes:
  - "http"
paths:
  /users:
    get:
      tags:
        - "user"
      summary: "Get all users"
      operationId: "getAllUsers"
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - "user"
      summary: "Create user"
      operationId: "createUser"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Create a user"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
  /users/{userId}:
    get:
      tags:
        - "user"
      summary: "Get a user"
      operationId: "getUser"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: Numeric ID of the user
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
    patch:
      tags:
        - "user"
      summary: "Update user"
      operationId: "updateUser"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: "Numeric ID of the user"
        - in: "body"
          name: "body"
          description: "Update a user object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
        - "user"
      summary: "Delete user"
      operationId: "deleteUser"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: Numeric ID of the user
        - in: "body"
          name: "body"
          description: "Delete a user object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
  /users/{userId}/notes:
    get:
      tags:
        - "note"
      summary: "Get all notes for user"
      operationId: "getAllNotesForUser"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: Numeric ID of the user
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Note"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - "note"
      summary: "Create a note for a user"
      operationId: "createNoteForUser"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: Numeric ID of the user
        - in: "body"
          name: "body"
          description: "Create a note for a user"
          required: true
          schema:
            $ref: "#/definitions/Note"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/Note"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
  /users/{userId}/notes/{noteId}:
    get:
      tags:
        - "note"
      summary: "Get a note for a user"
      operationId: "getNoteForUser"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: Numeric ID of the user
        - in: path
          name: noteId
          type: integer
          required: true
          description: Numeric ID of the note
        - in: "body"
          name: "body"
          description: "Create a note for a user"
          required: true
          schema:
            $ref: "#/definitions/Note"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Note"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
    patch:
      tags:
        - "note"
      summary: "Update note for user"
      operationId: "updateNoteForUser"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: Numeric ID of the user
        - in: path
          name: noteId
          type: integer
          required: true
          description: Numeric ID of the note
        - in: "body"
          name: "body"
          description: "Create a note for a user"
          required: true
          schema:
            $ref: "#/definitions/Note"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Note"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
        - "note"
      summary: "Delete user"
      operationId: "delete note for User"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: Numeric ID of the user
        - in: path
          name: noteId
          type: integer
          required: true
          description: Numeric ID of the note
        - in: "body"
          name: "body"
          description: "Create a note for a user"
          required: true
          schema:
            $ref: "#/definitions/Note"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Note"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"
        "415":
          description: "Unsuported MIME Type"
          schema:
            $ref: "#/definitions/Error"
        "418":
          description: "I am a teapot - if you code wrong this error will show"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Unprocessable entity"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        "501":
          description: "Not Implemented"
          schema:
            $ref: "#/definitions/Error"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      first_name:
        type: "string"
      last_name:
        type: "string"
      email_address:
        type: "string"
  Note:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      note:
        type: "string"
      user_id:
        type: "integer"
        format: "int64"
        readOnly: true
  Error:
    type: "object"
    properties:
      message:
        type: "string"
